/*
 * Product Mbed TLS USER_CONFIG overlay (Rev B size plan).
 * Included AFTER NXP mcux_mbedtls_config.h — only #undef / tighten.
 * Allow-list: TLS server, TLS1.2+1.3, ECDHE-ECDSA P-256, AES-GCM, SHA-256,
 * X.509 verify, PSA RNG. Do not weaken mTLS or remove IPv6 (lwIP separate).
 */
#ifndef MBEDTLS_PRODUCT_USER_CONFIG_H
#define MBEDTLS_PRODUCT_USER_CONFIG_H

/* ---- Key exchanges: keep ECDHE-ECDSA only ---- */
#undef MBEDTLS_KEY_EXCHANGE_PSK_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_DHE_PSK_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_RSA_PSK_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_RSA_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_DHE_RSA_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECDH_RSA_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED
/* KEEP: MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED */

/* ---- Legacy TLS / DTLS / extensions unused by product ---- */
#undef MBEDTLS_SSL_PROTO_SSL3
#undef MBEDTLS_SSL_PROTO_TLS1
#undef MBEDTLS_SSL_PROTO_TLS1_1
#undef MBEDTLS_SSL_PROTO_DTLS
#undef MBEDTLS_SSL_DTLS_ANTI_REPLAY
#undef MBEDTLS_SSL_DTLS_HELLO_VERIFY
#undef MBEDTLS_SSL_DTLS_CLIENT_PORT_REUSE
#undef MBEDTLS_SSL_DTLS_CONNECTION_ID
#undef MBEDTLS_SSL_DTLS_SRTP
#undef MBEDTLS_SSL_ALPN
#undef MBEDTLS_SSL_SERVER_NAME_INDICATION
#undef MBEDTLS_SSL_SESSION_TICKETS
#undef MBEDTLS_SSL_TICKET_C
#undef MBEDTLS_SSL_CACHE_C
#undef MBEDTLS_SSL_RENEGOTIATION
#undef MBEDTLS_SSL_CONTEXT_SERIALIZATION
#undef MBEDTLS_SSL_EARLY_DATA
#undef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_ENABLED
#undef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_EPHEMERAL_ENABLED
/* KEEP TLS 1.2 + TLS 1.3 (if enabled in NXP base) */

/* ---- MCU is TLS server only ---- */
#undef MBEDTLS_SSL_CLI_C
/* KEEP: MBEDTLS_SSL_SRV_C */

/* ---- Unused crypto / PKI tooling ---- */
#undef MBEDTLS_RSA_C
#undef MBEDTLS_DHM_C
#undef MBEDTLS_X509_RSASSA_PSS_SUPPORT
#undef MBEDTLS_PKCS1_V21
#undef MBEDTLS_DES_C
#undef MBEDTLS_CAMELLIA_C
#undef MBEDTLS_ARIA_C
#undef MBEDTLS_CHACHA20_C
#undef MBEDTLS_CHACHAPOLY_C
#undef MBEDTLS_POLY1305_C
#undef MBEDTLS_MD5_C
#undef MBEDTLS_SHA1_C
/* SHA-384/512: keep initially if TLS1.3 AES-256-GCM-SHA384 remains; measured later.
 * Plan retains AES-256/SHA-384 initially — do not undef SHA512 yet. */

#undef MBEDTLS_PKCS12_C
#undef MBEDTLS_PEM_WRITE_C
#undef MBEDTLS_X509_CRT_WRITE_C
#undef MBEDTLS_X509_CSR_WRITE_C
#undef MBEDTLS_X509_CREATE_C
#undef MBEDTLS_CERTS_C
#undef MBEDTLS_FS_IO
#undef MBEDTLS_NET_C
#undef MBEDTLS_DEBUG_C
#undef MBEDTLS_SELF_TEST
#undef MBEDTLS_ERROR_C
#undef MBEDTLS_VERSION_FEATURES
#undef MBEDTLS_SSL_ALL_ALERT_MESSAGES

/* Curves: P-256 only (NXP base may already narrow; reinforce) */
#undef MBEDTLS_ECP_DP_SECP192R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP224R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP384R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP521R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP192K1_ENABLED
#undef MBEDTLS_ECP_DP_SECP224K1_ENABLED
#undef MBEDTLS_ECP_DP_SECP256K1_ENABLED
#undef MBEDTLS_ECP_DP_BP256R1_ENABLED
#undef MBEDTLS_ECP_DP_BP384R1_ENABLED
#undef MBEDTLS_ECP_DP_BP512R1_ENABLED
#undef MBEDTLS_ECP_DP_CURVE25519_ENABLED
#undef MBEDTLS_ECP_DP_CURVE448_ENABLED
/* KEEP: MBEDTLS_ECP_DP_SECP256R1_ENABLED */

/* Cipher modes unused by AES-GCM profile */
#undef MBEDTLS_CIPHER_MODE_OFB
#undef MBEDTLS_CIPHER_MODE_XTS
#undef MBEDTLS_CIPHER_NULL_CIPHER
#undef MBEDTLS_ENABLE_WEAK_CIPHERSUITES

#endif /* MBEDTLS_PRODUCT_USER_CONFIG_H */
